version: '3.8'

services:
  #Database
  oracle-db:
    image:  container-registry.oracle.com/database/express:latest
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=123456
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./BD:/opt/oracle/scripts/setup
    healthcheck: 
      test: ["CMD", "bash", "-c", "sqlplus -L SYSTEM/123456 as SYSDBA << EOF\n SELECT 1 FROM DUAL;\n exit;\n EOF"] 
      interval: 10s 
      timeout: 5s   
      retries: 10   
      start_period: 120s 

    
    #API2
  ferremas-api2:
    build:
      context: ./API2
      dockerfile: Dockerfile
    container_name: api2-container
    ports:
      - "8080:8080"
    depends_on:
       oracle-db:
        condition: service_healthy
    environment:
     SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
     SPRING_DATASOURCE_USERNAME: FERREMAS
     SPRING_DATASOURCE_PASSWORD: FERREMAS
     SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.OracleDialect

  #API1
  ferremas-api1:
    build:
      context: ./API1
      dockerfile: Dockerfile
    container_name: api1-container
    ports:
      - "8000:8000"
    depends_on:
       oracle-db:
        condition: service_healthy
    environment: {}

  #Django
  django:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: django-container
    ports:
      - "8001:8000"
    depends_on:
        ferremas-api2:
          condition: service_started
        ferremas-api1:
          condition: service_started
    environment:
      DJANGO_SETTINGS_MODULE: ferremas.settings
      DEBUG: 'True'
      ALLOWED_HOSTS: 'localhost,127.0.0.1,django-container'
      API1_URL: http://ferremas-api1:8000
      API2_URL: http://ferremas-api2:8080
    volumes:
        - ./web:/app/web

volumes:
  oracle-data:
    driver: local

